// Code generated by protoc-gen-go.
// source: dragonfly.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	dragonfly.proto

It has these top-level messages:
	Task
	Result
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskType int32

const (
	TaskType_TEXT   TaskType = 1
	TaskType_IMAGE  TaskType = 2
	TaskType_JS     TaskType = 3
	TaskType_IFRAME TaskType = 4
)

var TaskType_name = map[int32]string{
	1: "TEXT",
	2: "IMAGE",
	3: "JS",
	4: "IFRAME",
}
var TaskType_value = map[string]int32{
	"TEXT":   1,
	"IMAGE":  2,
	"JS":     3,
	"IFRAME": 4,
}

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}
func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}
func (x *TaskType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskType_value, data, "TaskType")
	if err != nil {
		return err
	}
	*x = TaskType(value)
	return nil
}
func (TaskType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TaskStats int32

const (
	TaskStats_WAIT      TaskStats = 1
	TaskStats_SUCCESS   TaskStats = 2
	TaskStats_FAILUER   TaskStats = 3
	TaskStats_EXCEPTION TaskStats = 4
)

var TaskStats_name = map[int32]string{
	1: "WAIT",
	2: "SUCCESS",
	3: "FAILUER",
	4: "EXCEPTION",
}
var TaskStats_value = map[string]int32{
	"WAIT":      1,
	"SUCCESS":   2,
	"FAILUER":   3,
	"EXCEPTION": 4,
}

func (x TaskStats) Enum() *TaskStats {
	p := new(TaskStats)
	*p = x
	return p
}
func (x TaskStats) String() string {
	return proto.EnumName(TaskStats_name, int32(x))
}
func (x *TaskStats) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskStats_value, data, "TaskStats")
	if err != nil {
		return err
	}
	*x = TaskStats(value)
	return nil
}
func (TaskStats) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Task struct {
	Id               *string   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Channel          *string   `protobuf:"bytes,2,req,name=channel" json:"channel,omitempty"`
	Command          *string   `protobuf:"bytes,3,req,name=command" json:"command,omitempty"`
	Type             *TaskType `protobuf:"varint,4,req,name=type,enum=main.TaskType" json:"type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Task) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *Task) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *Task) GetType() TaskType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return TaskType_TEXT
}

type Result struct {
	Id               *string    `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Stats            *TaskStats `protobuf:"varint,2,req,name=stats,enum=main.TaskStats" json:"stats,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Result) GetStats() TaskStats {
	if m != nil && m.Stats != nil {
		return *m.Stats
	}
	return TaskStats_WAIT
}

func init() {
	proto.RegisterType((*Task)(nil), "main.Task")
	proto.RegisterType((*Result)(nil), "main.Result")
	proto.RegisterEnum("main.TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("main.TaskStats", TaskStats_name, TaskStats_value)
}

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0xce, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x71, 0x96, 0x65, 0xdd, 0xfa, 0xc4, 0x36, 0xe4, 0xd4, 0x83, 0x88, 0xec, 0x24, 0x3b,
	0xf4, 0x30, 0x3d, 0x0b, 0xa5, 0x64, 0x12, 0x71, 0x2a, 0x49, 0x86, 0xbb, 0x06, 0x5b, 0x75, 0xd8,
	0x26, 0x63, 0x89, 0x87, 0xfd, 0xf7, 0x26, 0x03, 0x2b, 0x1e, 0xdf, 0x0f, 0xbe, 0x1f, 0x1e, 0xe4,
	0xcd, 0x41, 0x7f, 0x58, 0xf3, 0xde, 0x1d, 0xcb, 0xfd, 0xc1, 0x7a, 0x4b, 0x71, 0xaf, 0x77, 0x66,
	0x2e, 0x00, 0x2b, 0xed, 0xbe, 0x28, 0x00, 0xda, 0x35, 0xc5, 0xe8, 0x0a, 0x5d, 0xa7, 0x34, 0x87,
	0xe9, 0xdb, 0xa7, 0x36, 0xa6, 0xed, 0x0a, 0x34, 0x0c, 0xb6, 0xef, 0xb5, 0x69, 0x8a, 0xf1, 0x69,
	0xb8, 0x00, 0xec, 0x8f, 0xfb, 0xb6, 0xc0, 0xe1, 0xca, 0x96, 0x59, 0x19, 0xa9, 0x32, 0x3a, 0x2a,
	0xac, 0xf3, 0x5b, 0x48, 0x44, 0xeb, 0xbe, 0x3b, 0xff, 0x4f, 0xbd, 0x84, 0x89, 0xf3, 0xda, 0xbb,
	0x93, 0x99, 0x2d, 0xf3, 0xbf, 0x48, 0xc6, 0x79, 0x71, 0x03, 0xb3, 0x5f, 0x81, 0xce, 0xc2, 0x57,
	0x6c, 0xab, 0xc8, 0x88, 0xa6, 0x30, 0xe1, 0xeb, 0xea, 0x9e, 0x11, 0x44, 0x13, 0x40, 0x0f, 0x92,
	0x8c, 0x03, 0x9a, 0xf0, 0x95, 0xa8, 0xd6, 0x8c, 0xe0, 0xc5, 0x1d, 0xa4, 0x83, 0x10, 0xab, 0xd7,
	0x8a, 0xc7, 0xea, 0x0c, 0xa6, 0x72, 0x53, 0xd7, 0x4c, 0xca, 0xd0, 0x85, 0x63, 0x55, 0xf1, 0xc7,
	0x0d, 0x13, 0x21, 0x3e, 0x87, 0x94, 0x6d, 0x6b, 0xf6, 0xa2, 0xf8, 0xf3, 0x13, 0xc1, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x6e, 0x1f, 0x20, 0x16, 0x01, 0x00, 0x00,
}
